name: Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_analyze:
    name: Build and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full history is available

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          REMOVED: ${{ secrets.REMOVED }} # Needed to get PR information, if any
          REMOVED: ${{ secrets.REMOVED }}

      - name: Wait for Quality Gate
        id: wait_quality_gate
        run: |
          echo "Waiting for Quality Gate analysis to finish..."
          sleep 60 # Wait for 60 seconds; adjust as necessary

          # Request Quality Gate status
          response=$(curl -s -u $REMOVED: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}")

          # Output response for debugging
          echo "Response from SonarCloud API: $response"

          # Check Quality Gate status
          status=$(echo $response | grep -oP '"status":"\K[^"]+')
          echo "Quality Gate status: $status"

          if [ "$status" != "OK" ]; then
            echo "Quality Gate failed: $response"
            exit 1
          else
            echo "Quality Gate passed"
          fi
